package main

import (
	"fmt"
	"log"
	"net/http"
)

func handleRoot(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "<head><link rel='stylesheet' type='text/css' href='css/standard.css'/></head>")
	fmt.Fprintf(w, "<div class='big-box'>")
	fmt.Fprintf(w, "<div class='green xlarge box'>Extra Large</div>")
	fmt.Fprintf(w, "<div class='green dlarge box'>Large</div>")
	fmt.Fprintf(w, "<div class='green large box'>Double Large</div>")
	fmt.Fprintf(w, "<div class='green dmedium box'>Double Medium</div>")
	fmt.Fprintf(w, "<div class='green medium box'>Medium</div>")
	fmt.Fprintf(w, "<div class='grey medium box'>Medium</div>")
	fmt.Fprintf(w, "<div class='green medium box'>Medium</div>")
	fmt.Fprintf(w, "<div class='green medium box'>Medium</div>")
	fmt.Fprintf(w, "<div class='green dsmall box'>Double Small</div>")
	fmt.Fprintf(w, "<div class='green dsmall box'>Double Small</div>")
	fmt.Fprintf(w, "<div class='grey dsmall box'>Double Small</div>")
	fmt.Fprintf(w, "<div class='grey small box'>Small</div>")
	fmt.Fprintf(w, "<div class='green small box'>Small</div>")
	fmt.Fprintf(w, "<div class='green small box'>Small</div>")
	fmt.Fprintf(w, "<div class='amber small box'>Small</div>")
	fmt.Fprintf(w, "<div class='green small box'>Small</div>")
	fmt.Fprintf(w, "<div class='green small box'>Small</div>")
	fmt.Fprintf(w, "<div class='green dmicro box'>D Micro</div>")
	fmt.Fprintf(w, "<div class='green dmicro box'>D Micro</div>")
	fmt.Fprintf(w, "<div class='red dmicro box'>D Micro</div>")
	fmt.Fprintf(w, "<div class='green dmicro box'>D Micro</div>")
	fmt.Fprintf(w, "<div class='green dmicro box'>D Micro</div>")
	fmt.Fprintf(w, "<div class='green micro box'>Micro</div>")
	fmt.Fprintf(w, "<div class='red micro box'>Micro</div>")
	fmt.Fprintf(w, "<div class='green micro box'>Micro</div>")
	fmt.Fprintf(w, "<div class='green micro box'>Micro</div>")
	fmt.Fprintf(w, "<div class='green micro box'>Micro</div>")
	fmt.Fprintf(w, "<div class='green micro box'>Micro</div>")
	fmt.Fprintf(w, "<div class='green micro box'>Micro</div>")
	fmt.Fprintf(w, "<div class='green micro box'>Micro</div>")
	fmt.Fprintf(w, "<div class='green micro box'>Micro</div>")
	fmt.Fprintf(w, "<div class='green micro box'>Micro</div>")
	fmt.Fprintf(w, "<div class='green micro box'>Micro</div>")
	fmt.Fprintf(w, "<div class='green micro box'>Micro</div>")
	fmt.Fprintf(w, "<div class='green micro box'>Micro</div>")
	fmt.Fprintf(w, "<div class='green micro box'>Micro</div>")
	fmt.Fprintf(w, "<div class='green micro box'>Micro</div>")
	fmt.Fprintf(w, "<div class='green micro box'>Micro</div>")
	fmt.Fprintf(w, "<div class='green micro box'>Micro</div>")
	fmt.Fprintf(w, "<div class='green micro box'>Micro</div>")
	fmt.Fprintf(w, "<div class='green micro box'>Micro</div>")
	fmt.Fprintf(w, "<div class='green micro box'>Micro</div>")
	fmt.Fprintf(w, "<div class='green micro box'>Micro</div>")
	fmt.Fprintf(w, "<div class='green micro box'>Micro</div>")
	fmt.Fprintf(w, "<div class='green micro box'>Micro</div>")
	fmt.Fprintf(w, "<div class='green micro box'>Micro</div>")
	fmt.Fprintf(w, "</div>")
}

func main() {
	http.HandleFunc("/", handleRoot)
	http.Handle("/css/", http.StripPrefix("/css/", http.FileServer(http.Dir("css/"))))
	log.Fatal(http.ListenAndServe(":8080", nil))
}
